name: 'Create Release'
description: 'Create a release on GitHub'
author: 'Théo Gillet - theocode-33'

# Define your inputs here.
inputs:
  version:
    description: 'The version of the release'
    required: true
  token:
    description: 'The GitHub token'
    required: true

runs:
  using: node18
  main: dist/index.js
